### PR TITLE
Ohm Playgrounds

### PR DESCRIPTION
**Pull request by mroeder**
Here are my changes to the Ohm Editor (so far) that add loading and saving Gists to the editor.
One feature, the forking, is still missing but I would like a review on the rest already.

PLEASE DON'T MERGE YET ;-)

### CODE REVIEW

**Comment by mroeder** [comment]
Addressed the comments above but only move style to `prompt.vue` (see 4bcebfb). I am not yet familiar with Vue.js but it might make sense to also extract the prompts HTML and logic to that file and just include it in `persistence.js`.

**Comment by pdubroy** [comment]
It definitely makes sense to move the HTML and JS logic to prompt.vue -- moving the style alone doesn't make much sense, as the whole point of .vue files is to be able to bundle HTML, JS, and CSS for a component into a single file. For now I think it would be best to put the CSS into a `.css` file, and to do the conversion to Vue in a separate PR.

One other small comment -- the name "prompt" seems a bit ambiguous to me, maybe "login" would be better?

Apart from that I think we should merge this ASAP...I'm looking forward to playing with it!

**Comment by mroeder** [comment]
Okay, I will revert my last commit that was putting stuff in a .vue file but as I tried to say, I don't know enough about Vue to do the next PR so maybe you can do that?

Regarding prompt, it really is a more general way to prompt for something and not just to login. It's used for logging in but als for asking for a grammar name (if you create a new one) and could be used for any other prompting we might need to do in the future.

**Comment by pdubroy** [comment]
> Regarding prompt, it really is a more general way to prompt for something and not just to login. It's used for logging in but als for asking for a grammar name (if you create a new one) and could be used for any other prompting we might need to do in the future.

Ok, makes sense.

**Pull request merged**
